AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TelegramTasweerBot-Lambda

Globals:
  Function:
    Timeout: 3

Parameters:
    StageEnv:
      Type: String
      AllowedValues:
        - dev
        - prod

Mappings:
  StageMappings:
    dev:
      stage: dev
    prod:
      stage: prod

Resources:
  TelegramTasweerBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: TelegramTasweerBot/
      Handler: TelegramTasweerBot_Lambda.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          stage: !FindInMap [StageMappings, !Ref StageEnv, stage]
          TelegramBotDynamoTable: !Ref TelegramTasweerBotTable
      MemorySize: 1024
      ReservedConcurrentExecutions: 10
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref TelegramTasweerBotTable
        - RekognitionDetectOnlyPolicy: {}
        - Statement:
          -
            Effect: "Allow"
            Action:
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Resource:
              - '*'
              - 'arn:aws:ssm:::parameter/telegramtasweerbot/*'
      Architectures:
        - x86_64
      Events:
        TelegramWebHook:
          Type: Api 
          Properties:
            Path: /
            Method: any
  TelegramTasweerBotTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: group
        Type: String

Outputs:
  TelegramApi:
    Description: "API Gateway endpoint URL for Prod stage for TelegramTasweerBot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
