AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TelegramTasweerBot-Lambda

Globals:
  Function:
    MemorySize: 1024
    Timeout: 9
    Runtime: python3.12
    LoggingConfig:
      LogGroup: !Sub /aws/lambda/${AWS::StackName}
      LogFormat: JSON
    Tags:
      project: "TelegramTasweerBot"
    Architectures:
      - arm64
    Environment:
      Variables:
        stage: !FindInMap [StageMappings, !Ref StageEnv, stage]
        POWERTOOLS_SERVICE_NAME: EmojiFaceVideo
        POWERTOOLS_METRICS_NAMESPACE: TelegramTasweerBot
    Layers:
      - !Sub "arn:aws:lambda:eu-west-1:580247275435:layer:LambdaInsightsExtension-Arm64:20"

Parameters:
    StageEnv:
      Type: String
      AllowedValues:
        - dev
        - prod

Mappings:
  StageMappings:
    dev:
      stage: dev
    prod:
      stage: prod

Resources:
  TelegramTasweerBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: TelegramTasweerBot/
      Handler: TelegramTasweerBot_Lambda.lambda_handler
      ReservedConcurrentExecutions: 10
      Policies:
        - RekognitionDetectOnlyPolicy: {}
        - Statement:
          - Effect: "Allow"
            Action:
              - ssm:GetParameters
              - ssm:GetParameter
              - ssm:GetParametersByPath
            Resource:
              - '*'
              - 'arn:aws:ssm:::parameter/telegramtasweerbot/*'
          - Effect: Allow
            Action: s3:*
            Resource: 
              - "arn:aws:s3:::telegramtasweerbot-dev-faceblur-in/*"
              - "arn:aws:s3:::telegramtasweerbot-dev-faceblur-out/*"
              - "arn:aws:s3:::telegramtasweerbot-prod-faceblur-in/*"
              - "arn:aws:s3:::telegramtasweerbot-prod-faceblur-out/*"
      Events:
        TelegramWebHook:
          Type: Api 
          Properties:
            Path: /
            Method: POST

Outputs:
  TelegramApi:
    Description: "API Gateway endpoint URL for Prod stage for TelegramTasweerBot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
