AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'TelegramTasweerBot-Lambda

  '
Globals:
  Function:
    Timeout: 3
Resources:
  TelegramFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: TelegramFunction
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
      - DynamoDBWritePolicy:
          TableName:
            Ref: TelegramBotTable
      - RekognitionDetectOnlyPolicy: {}
      Architectures:
      - x86_64
      Events:
        TelegramWebHook:
          Type: Api
          Properties:
            Path: /
            Method: any
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.TelegramFunction80a1c49eDepLayer
  TelegramBotTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: group
        Type: String
      TableName: MuslimPrivacyBot
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /Users/tokenadmin/WorkDocs/gitwork/python/telegram/NoHaraamImageBot/TelegramTasweerBot-Lambda/.aws-sam/auto-dependency-layer/nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  TelegramApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
